project:
  type: website

website:
  title: Dallas Dog
  navbar:
    right:
      - icon: github
        href: https://github.com/math241s24/project01-dog
    left:
      - text: "Project"
        href: Write_up.html
      - text: "Proposal"
        href: proposal.html
      - text: "Presentation"
        href: presentation.html
      - text: "About"
        href: about.html

format:
  html:
    theme: default
    toc: true

execute:
  freeze: auto